# config/development.toml

[database]
scheme = "postgres"
host = "localhost"
port = 5432
name = "booent_db"
username = "booent_user"
password = "booent_pass"

[server]
host = "127.0.0.1"
port = 8080

[jwt_data]
secret_key = "NwYumkQxcG/zEFqbBhOHSDmb65QLIkxwlARtxuKmLQM="

[google_config]
client_id = '816764122619-nqbtt71iv732ofgrt491r8s4n0ec2j9c.apps.googleusercontent.com'

[admin_data]
api_key = "test_admin"